// Export draft to PDF or DOCX (returned as base64 for client download).
import { createClient } from "https://esm.sh/@supabase/supabase-js@2.45.0";
import { Document, Packer, Paragraph, TextRun, HeadingLevel, AlignmentType } from "https://esm.sh/docx@8.5.0";
import { jsPDF } from "https://esm.sh/jspdf@2.5.1";

const corsHeaders = {
  "Access-Control-Allow-Origin": "*",
  "Access-Control-Allow-Headers":
    "authorization, x-client-info, apikey, content-type, x-supabase-client-platform, x-supabase-client-platform-version, x-supabase-client-runtime, x-supabase-client-runtime-version",
};

const SUPABASE_URL = Deno.env.get("SUPABASE_URL")!;
const SUPABASE_ANON_KEY = Deno.env.get("SUPABASE_PUBLISHABLE_KEY") ?? Deno.env.get("SUPABASE_ANON_KEY")!;

function bytesToBase64(bytes: Uint8Array): string {
  let binary = "";
  const chunk = 0x8000;
  for (let i = 0; i < bytes.length; i += chunk) {
    binary += String.fromCharCode(...bytes.subarray(i, i + chunk));
  }
  return btoa(binary);
}

async function makeDocx(title: string, content: string): Promise<Uint8Array> {
  const paragraphs: Paragraph[] = [
    new Paragraph({
      heading: HeadingLevel.TITLE,
      alignment: AlignmentType.CENTER,
      children: [new TextRun({ text: title, bold: true, size: 32 })],
    }),
    new Paragraph({ text: "" }),
  ];
  for (const block of content.split(/\n\n+/)) {
    paragraphs.push(new Paragraph({
      children: [new TextRun({ text: block, size: 22 })],
      spacing: { after: 160 },
    }));
  }
  const doc = new Document({ sections: [{ children: paragraphs }] });
  const blob = await Packer.toBlob(doc);
  return new Uint8Array(await blob.arrayBuffer());
}

function makePdf(title: string, content: string): Uint8Array {
  const doc = new jsPDF({ unit: "pt", format: "a4" });
  const pageW = doc.internal.pageSize.getWidth();
  const pageH = doc.internal.pageSize.getHeight();
  const margin = 56;
  const maxW = pageW - margin * 2;

  doc.setFont("times", "bold");
  doc.setFontSize(18);
  doc.text(title, pageW / 2, margin, { align: "center" });

  doc.setFont("times", "normal");
  doc.setFontSize(11);
  let y = margin + 36;
  const lineH = 16;
  const lines = doc.splitTextToSize(content, maxW);
  for (const line of lines) {
    if (y > pageH - margin) { doc.addPage(); y = margin; }
    doc.text(line, margin, y);
    y += lineH;
  }

  // Footer disclaimer on every page
  const pages = doc.getNumberOfPages();
  for (let i = 1; i <= pages; i++) {
    doc.setPage(i);
    doc.setFontSize(8);
    doc.setTextColor(120);
    doc.text(`Generated by NyayAI · AI-assisted draft — verify before filing · Page ${i} of ${pages}`, pageW / 2, pageH - 24, { align: "center" });
    doc.setTextColor(0);
  }

  return new Uint8Array(doc.output("arraybuffer"));
}

Deno.serve(async (req) => {
  if (req.method === "OPTIONS") return new Response(null, { headers: corsHeaders });

  try {
    const auth = req.headers.get("Authorization");
    if (!auth) return json({ error: "Unauthorized" }, 401);

    const userClient = createClient(SUPABASE_URL, SUPABASE_ANON_KEY, {
      global: { headers: { Authorization: auth } },
    });
    const { data: { user } } = await userClient.auth.getUser();
    if (!user) return json({ error: "Unauthorized" }, 401);

    const { draft_id, format } = await req.json();
    if (!draft_id || !["pdf", "docx"].includes(format)) {
      return json({ error: "draft_id and format (pdf|docx) required" }, 400);
    }

    const { data: draft, error } = await userClient
      .from("drafts")
      .select("title, content")
      .eq("id", draft_id)
      .maybeSingle();
    if (error || !draft) return json({ error: "Draft not found" }, 404);

    const bytes = format === "docx"
      ? await makeDocx(draft.title, draft.content || "")
      : makePdf(draft.title, draft.content || "");

    return json({ file: bytesToBase64(bytes), filename: `${draft.title}.${format}` });
  } catch (e) {
    console.error("export-draft error", e);
    return json({ error: e instanceof Error ? e.message : "Unknown error" }, 500);
  }
});

function json(body: unknown, status = 200) {
  return new Response(JSON.stringify(body), {
    status,
    headers: { ...corsHeaders, "Content-Type": "application/json" },
  });
}
